# Generated by Django 6.0.6 on 2026-09-21 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_image_formats', models.CharField(default='jpg,jpeg,png', help_text='Comma-separated image extensions, no dots.', max_length=100)),
                ('allowed_video_formats', models.CharField(default='mp4,avi,mov', help_text='Comma-separated video extensions, no dots.', max_length=100)),
                ('max_upload_mb', models.IntegerField(default=512, help_text='Maximum size of a single upload, in megabytes.')),
                ('max_video_seconds', models.IntegerField(default=300, help_text='Longest video clip accepted, in seconds.')),
                ('confidence_threshold', models.FloatField(default=0.35, help_text='Minimum detector confidence for a vehicle to count (0-1).')),
                ('smoke_mask_threshold', models.FloatField(default=0.5, help_text='Probability cut-off that binarises the smoke mask (0-1).')),
                ('severity_low_max', models.FloatField(default=0.33, help_text='Intensity at or below this is "low".')),
                ('severity_moderate_max', models.FloatField(default=0.66, help_text='Intensity at or below this is "moderate"; above is "high".')),
                ('frame_sample_rate', models.IntegerField(default=5, help_text='Analyse every Nth frame of a video.')),
                ('auto_generate_pdf', models.BooleanField(default=True, help_text='Produce a PDF report automatically when a run completes.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system configuration',
                'verbose_name_plural': 'system configuration',
                'db_table': 'sysconfig_system_setting',
            },
        ),
    ]
