# Generated by Django 6.0.6 on 2026-09-21 17:04

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='user ID')),
                ('email', models.EmailField(db_index=True, help_text='Used as the login identifier.', max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Administrator')], db_index=True, default='user', help_text="'admin' unlocks the system-configuration screens.", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of deleting to preserve analysis history.')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
                'ordering': ('-created_at',),
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='token ID')),
                ('token', models.CharField(db_index=True, default=accounts.models.generate_reset_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models.default_reset_expiry)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'password reset token',
                'verbose_name_plural': 'password reset tokens',
                'db_table': 'accounts_password_reset_token',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'used'], name='pwreset_user_used_idx')],
            },
        ),
    ]
