"""
Views for the system-configuration API (UC-09): a single object endpoint over
the :class:`~system_config.models.SystemSetting` singleton.

Both verbs live on one view because there is exactly one resource — there is
no list, no id in the URL, nothing to route besides "read it" and "change
it". Authentication (and therefore the anonymous-gets-401 behaviour) comes
for free from ``REST_FRAMEWORK['DEFAULT_PERMISSION_CLASSES']``
(``IsAuthenticated``); the admin-only write is enforced by hand in
:meth:`SystemSettingsView.patch` so the 403 carries the exact
``code: "admin_required"`` the contract promises rather than DRF's generic
``permission_denied``.
"""
import logging

from drf_spectacular.utils import OpenApiExample, extend_schema
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from common.exceptions import error_response

from .models import SystemSetting
from .serializers import SystemSettingSerializer

logger = logging.getLogger('asg.sysconfig')

#: Shared by both @extend_schema blocks below so the docs show one
#: realistic, contract-shaped payload instead of an autogenerated stub.
_EXAMPLE_SETTINGS = {
    'allowed_image_formats': ['jpg', 'jpeg', 'png'],
    'allowed_video_formats': ['mp4', 'avi', 'mov'],
    'max_upload_mb': 512,
    'confidence_threshold': 0.35,
    'smoke_mask_threshold': 0.5,
    'severity_low_max': 0.33,
    'severity_moderate_max': 0.66,
    'frame_sample_rate': 5,
    'auto_generate_pdf': True,
    'max_video_seconds': 300,
    'updated_at': '2026-09-21T10:15:00Z',
    'updated_by': 'admin@example.com',
    'runtime': {
        'device': 'mps',
        'segmenter_mode': 'unet',
        'yolo_weights_present': True,
        'segmenter_weights_present': True,
        'worker_threads': 2,
        'model_metrics': {'dice': 0.87, 'iou': 0.79, 'pixel_accuracy': 0.94},
    },
}


class SystemSettingsView(APIView):
    """
    ``GET`` / ``PATCH`` the runtime configuration singleton.

    ``GET`` is readable by any authenticated user — the Upload screen needs
    the current size/format limits before it lets someone pick a file.
    ``PATCH`` is restricted to ``role == 'admin'``; everyone else, including
    staff-flagged accounts that are not administrators, gets a 403.
    """

    def get_object(self):
        """Fetch (or lazily create) the one configuration row."""
        return SystemSetting.get_solo()

    @extend_schema(
        summary='Get the current system configuration',
        description=(
            'Read the runtime upload limits, model thresholds, severity '
            'banding and pipeline behaviour, plus a computed `runtime` '
            'block describing the device and model assets in use. Any '
            'authenticated user may call this.'
        ),
        responses={200: SystemSettingSerializer},
        examples=[
            OpenApiExample(
                'Current configuration',
                value=_EXAMPLE_SETTINGS,
                response_only=True,
            ),
        ],
    )
    def get(self, request):
        instance = self.get_object()
        serializer = SystemSettingSerializer(instance, context={'request': request})
        return Response(serializer.data)

    @extend_schema(
        summary='Update the system configuration',
        description=(
            'Partially update upload limits, model thresholds, severity '
            'banding or pipeline behaviour. Administrator-only '
            '(`role == "admin"`); anyone else receives '
            '403 `admin_required`. Unspecified fields are left unchanged. '
            'Every accepted change is written to the `asg.sysconfig` audit '
            'log as a before/after diff.'
        ),
        request=SystemSettingSerializer,
        responses={200: SystemSettingSerializer},
        examples=[
            OpenApiExample(
                'Raise the confidence threshold',
                value={'confidence_threshold': 0.45},
                request_only=True,
            ),
            OpenApiExample(
                'Updated configuration',
                value={**_EXAMPLE_SETTINGS, 'confidence_threshold': 0.45},
                response_only=True,
            ),
        ],
    )
    def patch(self, request):
        if getattr(request.user, 'role', None) != 'admin':
            logger.warning(
                'Non-admin %s attempted to PATCH /api/settings.',
                getattr(request.user, 'email', request.user),
            )
            return error_response(
                'Administrator access required.',
                'admin_required',
                status.HTTP_403_FORBIDDEN,
            )

        instance = self.get_object()
        serializer = SystemSettingSerializer(
            instance, data=request.data, partial=True,
            context={'request': request},
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
