# Generated by Django 6.0.6 on 2026-09-21 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='report ID')),
                ('report_path', models.CharField(help_text='PDF location, relative to MEDIA_ROOT.', max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('page_count', models.IntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='analysis.analysisresult')),
            ],
            options={
                'verbose_name': 'generated report',
                'verbose_name_plural': 'generated reports',
                'db_table': 'reports_generated_report',
                'ordering': ('-generated_at',),
                'indexes': [models.Index(fields=['generated_at'], name='report_generated_idx')],
            },
        ),
    ]
