# Generated by Django 6.0.6 on 2026-09-21 17:04

import analysis.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('analysis_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='analysis ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Completion percentage, 0-100.')),
                ('stage', models.CharField(blank=True, help_text="Human-readable step, e.g. 'segmenting frames'.", max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_vehicles', models.IntegerField(default=0)),
                ('total_smoke', models.IntegerField(default=0, help_text='Number of smoke regions detected across all vehicles.')),
                ('frames_processed', models.IntegerField(default=0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('overall_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('severity_counts', models.JSONField(default=analysis.models.default_severity_counts, help_text='{"low": n, "moderate": n, "high": n}')),
                ('settings_snapshot', models.JSONField(default=dict, help_text='Thresholds and sampling rate in force when this ran.')),
                ('preview_path', models.CharField(blank=True, help_text='Annotated preview image, relative to MEDIA_ROOT.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='uploads.uploadedmedia')),
                ('user', models.ForeignKey(help_text='Denormalised from media.user for fast history queries.', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'analysis result',
                'verbose_name_plural': 'analysis results',
                'db_table': 'analysis_result',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DetectedVehicle',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='vehicle ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus'), ('motorcycle', 'Motorcycle')], max_length=30)),
                ('bounding_box', models.JSONField(default=dict, help_text='Pixel box in source coordinates: {"x":, "y":, "w":, "h":}.')),
                ('confidence', models.FloatField(help_text='Detector confidence, 0-1.')),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('timestamp_seconds', models.FloatField(blank=True, null=True)),
                ('crop_path', models.CharField(blank=True, help_text='Cropped vehicle image, relative to MEDIA_ROOT.', max_length=500)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='analysis.analysisresult')),
            ],
            options={
                'verbose_name': 'detected vehicle',
                'verbose_name_plural': 'detected vehicles',
                'db_table': 'analysis_detected_vehicle',
                'ordering': ('frame_number', '-confidence'),
            },
        ),
        migrations.CreateModel(
            name='SmokeRegion',
            fields=[
                ('smoke_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='smoke ID')),
                ('mask_path', models.CharField(blank=True, help_text='Binary segmentation mask, relative to MEDIA_ROOT.', max_length=500)),
                ('intensity', models.FloatField(help_text='Normalised smoke intensity, 0-1.')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('confidence', models.FloatField(help_text='Segmenter confidence, 0-1.')),
                ('area_ratio', models.FloatField(default=0.0, help_text='Mask area as a fraction of the vehicle bounding box.')),
                ('opacity', models.FloatField(default=0.0, help_text='Mean opacity of the mask, 0-1.')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smoke_regions', to='analysis.detectedvehicle')),
            ],
            options={
                'verbose_name': 'smoke region',
                'verbose_name_plural': 'smoke regions',
                'db_table': 'analysis_smoke_region',
                'ordering': ('-intensity',),
            },
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['user', 'created_at'], name='analysis_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['status'], name='analysis_status_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedvehicle',
            index=models.Index(fields=['analysis', 'frame_number'], name='vehicle_analysis_frame_idx'),
        ),
        migrations.AddIndex(
            model_name='smokeregion',
            index=models.Index(fields=['vehicle', 'severity'], name='smoke_vehicle_severity_idx'),
        ),
    ]
