# Generated by Django 6.0.6 on 2026-09-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='report_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='State of the PDF report for this run.', max_length=20),
        ),
    ]
