# Generated by Django 6.0.6 on 2026-09-21 17:04

import common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('media_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='media ID')),
                ('filename', models.CharField(help_text='Original client-supplied filename, for display only.', max_length=255)),
                ('format', models.CharField(choices=[('jpg', 'JPEG'), ('png', 'PNG'), ('mp4', 'MP4'), ('avi', 'AVI'), ('mov', 'QuickTime')], max_length=10)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('size_bytes', models.BigIntegerField()),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(max_length=500, upload_to=common.storage.user_media_path)),
                ('file_path', models.CharField(blank=True, help_text='Storage-relative path; mirrors file.name.', max_length=500)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Videos only; null for stills.', null=True)),
                ('checksum', models.CharField(blank=True, db_index=True, help_text='SHA-256 of the file contents; identifies re-uploads.', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uploaded media',
                'verbose_name_plural': 'uploaded media',
                'db_table': 'uploads_media',
                'ordering': ('-upload_timestamp',),
                'indexes': [models.Index(fields=['user', 'upload_timestamp'], name='media_user_uploaded_idx')],
            },
        ),
    ]
